### ISSUE TITLE
backend code is missing

### ISSUE THREAD

**Issue by holygekko** [GalloDaSballo/strapi-profile#2]
I came here after watching the udemy Complete Strapi Course, but I believe the backend code is missing here. It's an empty project.

Love the course and looking forward to the code examples!

**Comment by GalloDaSballo** [comment]
Hey @holygekko, the code is all here.
Download the entire repo with git clone

Then enter profile-backend (the strapi install), and run
`npm i`

Then enter profile-server and run (this is the server that will serve the frontend)
`npm i` 

Then enter profile-frontend and run
`npm i`

Let me know how it goes!

**Comment by holygekko** [comment]
Ah I see it now, my mistake. Thanks!
